// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqXc3C-njQkBLZrO_t35b6owH6ogxECh8',
    appId: '1:173313453652:web:9bd97b01c8fb9ea28ac7c1',
    messagingSenderId: '173313453652',
    projectId: 'yelp2-38e67',
    authDomain: 'yelp2-38e67.firebaseapp.com',
    storageBucket: 'yelp2-38e67.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhmxvte73Z-oIDo_c6Bb7SRJEkrsDJ_xo',
    appId: '1:173313453652:android:14bbf30563d7c0c98ac7c1',
    messagingSenderId: '173313453652',
    projectId: 'yelp2-38e67',
    storageBucket: 'yelp2-38e67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9rmYdQLO0QftAKFY3rU1UdTJZcWcA2V8',
    appId: '1:173313453652:ios:8cf7d0fd7e263d3c8ac7c1',
    messagingSenderId: '173313453652',
    projectId: 'yelp2-38e67',
    storageBucket: 'yelp2-38e67.appspot.com',
    iosClientId: '173313453652-dgei7milin2c19ej2p44lfruffc54de3.apps.googleusercontent.com',
    iosBundleId: 'com.example.yelp2',
  );
}
